version: 0.1
connectors:
  - id: api.monitoring
    kind: http
    endpoints:
      - name: health
        url: https://example.org/api/health
      - name: metrics
        url: https://example.org/api/metrics
    slo_expectations:
      latency_p95_ms: 800
      error_rate: 0.01
secrets:
  provider: env|vault
  keys:
    - name: API_TOKEN
      path: MCAG/API_TOKEN
